#2 = Snow
skins.2=2
biomes.2=DeepFrozenOcean IceSpikes SnowyBeach SnowyPlains SnowyTaiga SnowySlopes FrozenRiver FrozenOcean FrozenPeaks Grove JaggedPeaks

#3 = Desert
skins.3=3
biomes.3=desert badlands eroded_badlands wooded_badlands

#4 = Green camo
skins.4=4
biomes.4=old_growth_spruce_taiga taiga old_growth_pine_taiga mangrove_swamp 